name: Build Samsung A30s NetHunter Kernel

on:
  workflow_dispatch: # Allows you to trigger the build manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git build-essential libncurses5-dev bison flex libssl-dev bc libelf-dev ccache cpio zip
        - name: Download Clang Toolchain
        run: |
        mkdir -p $GITHUB_WORKSPACE/clang
        cd $GITHUB_WORKSPACE/clang
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/refs/heads/main/clang-r416183b1.tar.gz
        tar -xf clang-r416183b1.tar.gz
         rm clang-r416183b1.tar.gz

    - name: Download Proton Clang
      run: |
        git clone https://github.com/kdrag0n/proton-clang --depth=1 $GITHUB_WORKSPACE/clang


    - name: Package with AnyKernel3
      run: |
       git clone https://github.com/SecureAuthCorp/AndroidKiller $GITHUB_WORKSPACE/AnyKernel3
        cd $GITHUB_WORKSPACE/AnyKernel3 && zip -r9 nethunter-kernel-a30s.zip *

    - name: Upload Flashable Zip
      uses: actions/upload-artifact@v4
      with:
        name: NetHunter-Kernel-A30s
        path: ${{ github.workspace }}/AnyKernel3/nethunter-kernel-a30s.zip
